"""LiteLLM proxy callback: one JSON line per model call with token usage, for exact per-model/per-task accounting.

Enabled from litellm.yaml (`callbacks: usage_logger.proxy_handler_instance`, generated by scripts/registry.py).
Writes to $AGENTRT_USAGE_LOG (default: agentrt-usage.jsonl in the system temp dir). Records counts and timing
only: no prompts, completions, keys or URLs.
"""
import json
import os
import tempfile
import threading
import time

from litellm.integrations.custom_logger import CustomLogger

_LOCK = threading.Lock()


def _get(obj, *path, default=0):
    for p in path:
        if obj is None:
            return default
        obj = obj.get(p) if isinstance(obj, dict) else getattr(obj, p, None)
    return obj if obj is not None else default


class UsageLogger(CustomLogger):
    def __init__(self):
        super().__init__()
        self.path = os.environ.get("AGENTRT_USAGE_LOG") or os.path.join(tempfile.gettempdir(), "agentrt-usage.jsonl")

    def _write(self, record: dict):
        with _LOCK, open(self.path, "a") as f:
            f.write(json.dumps(record) + "\n")

    async def async_log_success_event(self, kwargs, response_obj, start_time, end_time):
        slo = kwargs.get("standard_logging_object") or {}
        usage = _get(response_obj, "usage", default=None)
        choices = _get(response_obj, "choices", default=None) or []
        finish = _get(choices[0], "finish_reason", default=None) if choices else None
        self._write({
            "ts": time.time(),
            "alias": slo.get("model_group") or kwargs.get("model"),
            "call_type": slo.get("call_type"),
            "input_tokens": slo.get("prompt_tokens") or _get(usage, "prompt_tokens"),
            "output_tokens": slo.get("completion_tokens") or _get(usage, "completion_tokens"),
            "cache_read_tokens": _get(usage, "prompt_tokens_details", "cached_tokens")
            or _get(usage, "cache_read_input_tokens"),
            "cache_write_tokens": _get(usage, "cache_creation_input_tokens"),
            "finish_reason": finish,
            "latency_s": round(slo.get("response_time") or 0, 3),
        })

    async def async_log_failure_event(self, kwargs, response_obj, start_time, end_time):
        slo = kwargs.get("standard_logging_object") or {}
        self._write({"ts": time.time(), "alias": slo.get("model_group") or kwargs.get("model"), "error": True,
                     "input_tokens": 0, "output_tokens": 0, "cache_read_tokens": 0, "cache_write_tokens": 0})


proxy_handler_instance = UsageLogger()
