"""Harness + model registry: the one place that knows which harnesses and model aliases exist.

Library (import from qa/ and quality/):   from registry import harnesses, models, port
CLI (shell scripts, Makefile):
    registry.py names                         harness names, space-separated
    registry.py port <harness> <purpose>      e.g. port strands qa -> 18401
    registry.py get <harness> <field>         e.g. get pi language -> node
    registry.py models [--qa|--red-team|--real]  comma-separated aliases
    registry.py gen [--check]                 (re)generate litellm.yaml, compose harness services, k8s overlays
    registry.py new-harness <name> <python|node>   scaffold from harnesses/_templates/<lang>, register, gen

Stdlib only (Python >= 3.11).
"""
import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
HARNESS_FILE = ROOT / "harnesses.toml"
MODEL_FILE = ROOT / "models.toml"
GENERATED = "# GENERATED by scripts/registry.py from {src}. Do not edit; run `make gen`.\n"
NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,30}$")


def _load(path: pathlib.Path) -> dict:
    return tomllib.loads(path.read_text())


def harnesses() -> list[dict]:
    hs = _load(HARNESS_FILE)["harness"]
    seen = set()
    for h in hs:
        if not NAME_RE.match(h["name"]) or not 1 <= h["index"] <= 19 or h["index"] in seen:
            raise ValueError(f"invalid harness entry {h}: name [a-z0-9-], unique index 1..19")
        if h["language"] not in ("python", "node"):
            raise ValueError(f"{h['name']}: language must be python or node")
        seen.add(h["index"])
    return hs


def harness(name: str) -> dict:
    for h in harnesses():
        if h["name"] == name:
            return h
    raise KeyError(f"unknown harness {name!r}; known: {', '.join(names())}")


def runtimes() -> list[dict]:
    """Harness-specific runtimes ([[runtime]] in harnesses.toml)."""
    rs = _load(HARNESS_FILE).get("runtime", [])
    for r in rs:
        unknown = set(r["harnesses"]) - set(names())
        if unknown or r["kind"] != "container":
            raise ValueError(f"invalid runtime entry {r}: unknown harness {unknown} or kind")
        if r["kind"] == "container" and not isinstance(r.get("port_base"), int):
            raise ValueError(f"runtime {r['name']}: kind container needs an integer port_base")
        if r.get("egress", "open") not in ("open", "proxy-only"):
            raise ValueError(f"runtime {r['name']}: egress must be open or proxy-only")
    return rs


def egress(runtime: str) -> str:
    """open | proxy-only (scripts/egress_gw.py)."""
    return next(r for r in runtimes() if r["name"] == runtime).get("egress", "open")


def sandboxes() -> list[dict]:
    """Sandboxes for the QA box suite ([[sandbox]] in harnesses.toml); harnesses "*" expanded."""
    out = []
    for s in _load(HARNESS_FILE).get("sandbox", []):
        hs = names() if s["harnesses"] == ["*"] else s["harnesses"]
        unknown = set(hs) - set(names())
        if not NAME_RE.match(s["name"]) or unknown or s["exec"] not in ("simulated", "box", "strands-sandbox"):
            raise ValueError(f"invalid sandbox entry {s}: name, unknown harness {unknown} or exec")
        if s.get("runtime") and s["runtime"] not in {r["name"] for r in runtimes()}:
            raise ValueError(f"sandbox {s['name']}: unknown runtime {s['runtime']}")
        out.append({**s, "harnesses": hs})
    return out


def images() -> list[str]:
    """Docker build contexts outside harnesses/: container runtimes and sandbox images (runtimes/<name>)."""
    return [r["name"] for r in runtimes()] + sorted({s["image"] for s in sandboxes() if s.get("image")})


def port_shift() -> int:
    """AGENTRT_PORT_SHIFT (0, 20, 40, 60): lets several QA processes (one per model) run side by side. Each [ports]
    range is 100 wide and harness indexes stay below 20, so shifted ranges never overlap."""
    shift = int(os.environ.get("AGENTRT_PORT_SHIFT") or 0)
    if shift % 20 or not 0 <= shift <= 60:
        raise ValueError(f"AGENTRT_PORT_SHIFT must be 0, 20, 40 or 60, not {shift}")
    return shift


def runtime_port(runtime: dict, name: str) -> int:
    """Host port of harness `name` on a container runtime (its own range, so it never clashes with docker_local)."""
    return runtime["port_base"] + harness(name)["index"] + port_shift()


def names() -> list[str]:
    return [h["name"] for h in harnesses()]


def ports() -> dict:
    return _load(HARNESS_FILE)["ports"]


def port(name: str, purpose: str) -> int:
    return ports()[purpose] + harness(name)["index"] + port_shift()


def start_command(name: str, port_: int) -> list[str]:
    """Command (run inside harnesses/<name>) that serves the contract on port_."""
    if harness(name)["language"] == "node":
        return ["node", "dist/server.js"]  # reads PORT
    return ["uv", "run", "uvicorn", "app:app", "--host", "127.0.0.1", "--port", str(port_)]


def models() -> list[dict]:
    return _load(MODEL_FILE)["model"]


PROVIDERS = {  # provider -> (litellm custom_llm_provider, required env fields, optional env fields)
    "openai_compatible": ("openai", ("base_url", "api_key", "model"), ()),
    "openrouter": ("openrouter", ("api_key", "model"), ()),
    "bedrock": ("bedrock", ("model", "region"), ("aws_profile",)),
}


def provider(m: dict) -> str:
    p = m.get("provider", "openai_compatible")
    if m["kind"] != "mock" and p not in PROVIDERS:
        raise ValueError(f"model {m['alias']}: provider must be one of {', '.join(PROVIDERS)}")
    return p


def model_env_vars(m: dict, required_only: bool = False) -> list[str]:
    if m["kind"] == "mock":
        return []
    _, req, opt = PROVIDERS[provider(m)]
    return [m[k] for k in req + (() if required_only else opt) if m.get(k)]


def load_dotenv(path: pathlib.Path = ROOT / ".env") -> None:
    """KEY=VALUE lines into os.environ (existing env wins). Values never leave the process."""
    import os
    if path.exists():
        for line in path.read_text().splitlines():
            m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
            if m and m.group(1) not in os.environ:
                os.environ[m.group(1)] = m.group(2).strip().strip('"').strip("'")


def missing_env(m: dict) -> list[str]:
    import os
    return [v for v in model_env_vars(m, required_only=True) if not os.environ.get(v)]


# ---------------------------------------------------------------- generators

def gen_litellm() -> str:
    out = [GENERATED.format(src="models.toml"),
           "# Model aliases are the only thing harnesses know about. Values come from .env.\n", "model_list:\n"]
    for m in models():
        if m["kind"] == "mock":
            out.append(f"  - model_name: {m['alias']}   # deterministic canary script (compat/mock-llm)\n"
                       "    litellm_params:\n      model: openai/mock\n      api_base: os.environ/MOCK_LLM_BASE_URL\n"
                       "      api_key: unused\n")
        else:
            prov = provider(m)
            out.append(f"  - model_name: {m['alias']}   # kind: {m['kind']}, provider: {prov}\n    litellm_params:\n"
                       f"      model: os.environ/{m['model']}\n      custom_llm_provider: {PROVIDERS[prov][0]}\n")
            if m.get("base_url"):
                out.append(f"      api_base: os.environ/{m['base_url']}\n")
            if m.get("api_key"):
                out.append(f"      api_key: os.environ/{m['api_key']}\n")
            if m.get("drop_params"):  # upstream rejects some OpenAI params (e.g. vLLM reasoning_effort values)
                out.append(f"      additional_drop_params: {json.dumps(m['drop_params'])}\n")
            if prov == "bedrock":
                out.append(f"      aws_region_name: os.environ/{m['region']}\n")
                if m.get("aws_profile"):
                    out.append(f"      aws_profile_name: os.environ/{m['aws_profile']}\n")
    out.append("\nlitellm_settings:\n  drop_params: true\n"
               "  # Anthropic-API harnesses (claude-code) reach every upstream via chat/completions, like the others\n"
               "  use_chat_completions_url_for_anthropic_messages: true\n"
               "  callbacks: usage_logger.proxy_handler_instance   # per-call token usage -> $AGENTRT_USAGE_LOG\n"
               "\ngeneral_settings:\n"
               "  master_key: os.environ/LITELLM_MASTER_KEY\n")
    return "".join(out)


X_AGENT = """x-agent: &agent
  restart: unless-stopped
  security_opt: [no-new-privileges:true]
  cap_drop: [ALL]
  depends_on: {litellm: {condition: service_healthy}}
  environment: &agent-env
    OPENAI_BASE_URL: http://litellm:4000/v1
    OPENAI_API_KEY: ${LITELLM_MASTER_KEY}
    MODEL: ${MODEL:-mock}
    OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_ENDPOINT:-}   # empty = tracing off
    OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    OTEL_EXPORTER_OTLP_HEADERS: Authorization=Basic ${LANGFUSE_BASIC_AUTH}
    CANARY_FIXTURE: /app/canary.json
"""


# Mirrors run_container() in github.com/schubergphilis/claude-docker run.sh (v0.3.3): tini init, no new privileges,
# all capabilities dropped except the four its entrypoint needs to drop root (they are inert afterwards), credential
# directories masked with tmpfs, and no persistent volumes (its --ephemeral mode). One list for compose, k8s and
# `docker run` (runtimes/claude-docker/run.sh and the QA runner's container launch).
CLAUDE_DOCKER_CAPS = ("CHOWN", "SETUID", "SETGID", "DAC_READ_SEARCH")
CLAUDE_DOCKER_TMPFS = ("/root/.aws", "/root/.config/gh", "/root/.config/glab-cli", "/root/.terraform.d", "/root/.azure")
CLAUDE_DOCKER_GUARDRAILS = f"""    init: true
    security_opt: [no-new-privileges:true]
    cap_drop: [ALL]
    cap_add: [{", ".join(CLAUDE_DOCKER_CAPS)}]
    tmpfs: [{", ".join(CLAUDE_DOCKER_TMPFS)}]
"""
RUNTIME_RUN_ARGS = {
    "claude-docker": ["--init", "--security-opt", "no-new-privileges", "--cap-drop", "ALL",
                      *[x for c in CLAUDE_DOCKER_CAPS for x in ("--cap-add", c)],
                      *[x for d in CLAUDE_DOCKER_TMPFS for x in ("--tmpfs", d)],
                      "-e", "HOST_UID=10001", "-e", "HOST_GID=10001"],
}


def run_args(runtime: str) -> list[str]:
    if runtime not in {r["name"] for r in container_runtimes()}:
        raise KeyError(f"unknown container runtime {runtime!r}")
    return RUNTIME_RUN_ARGS.get(runtime, ["--security-opt", "no-new-privileges", "--cap-drop", "ALL"])


def gen_compose() -> str:
    out = [GENERATED.format(src="harnesses.toml"),
           "# Harness services; combined with docker-compose.yml (see Makefile COMPOSE).\n",
           X_AGENT, "\nservices:\n"]
    for h in harnesses():
        n = h["name"]
        out.append(f"  {n}:\n    <<: *agent\n    build: {{context: ../.., dockerfile: harnesses/{n}/Dockerfile}}\n"
                   f"    image: agentrt/{n}:dev\n    ports: [\"127.0.0.1:{port(n, 'docker_local')}:8080\"]\n"
                   f"    environment: {{<<: *agent-env, OTEL_SERVICE_NAME: agent-{n}}}\n    profiles: [{n}, all]\n")
        out.append("\n")
    return "".join(out)


def gen_compose_runtime(r: dict) -> str:
    """Compose file for a container runtime: its listed harnesses on runtimes/<name>/Dockerfile."""
    rn = r["name"]
    env, guardrails, _ = RUNTIME_EXTRAS.get(rn, ("", "", ""))
    out = [GENERATED.format(src="harnesses.toml"),
           f"# {rn} runtime: {', '.join(r['harnesses'])} on the {rn} image (runtimes/{rn}/Dockerfile).\n"
           f"# Combined with runtimes/docker-local/docker-compose.yml (see Makefile up-{rn}).\n",
           X_AGENT, "\nservices:\n"]
    proxy_only = r.get("egress", "open") == "proxy-only"
    net = f"{rn}-egress"
    for n in r["harnesses"]:
        svc = f"{n}-{rn}"
        # proxy-only: the agent is on an internal network only, so Docker does not publish its port; the gateway does
        ports = f"    networks: [{net}]\n" if proxy_only else f"    ports: [\"127.0.0.1:{runtime_port(r, n)}:8080\"]\n"
        out.append(f"  {svc}:\n    <<: *agent\n    build: {{context: ../.., dockerfile: runtimes/{rn}/Dockerfile}}\n"
                   f"    image: agentrt/{n}:{rn}\n{ports}"
                   f"    environment: {{<<: *agent-env, OTEL_SERVICE_NAME: agent-{n}{env}}}\n"
                   f"    profiles: [{rn}]\n{guardrails}")
        if proxy_only:
            out.append(f"  {svc}-gw:   # inbound API port only (scripts/egress_gw.py, same image)\n"
                       "    build: {context: ../egress-gw}\n    image: agentrt/egress-gw:dev\n"
                       f"    ports: [\"127.0.0.1:{runtime_port(r, n)}:8080\"]\n    networks: [default, {net}]\n"
                       f"    command: [\"socat TCP-LISTEN:8080,fork,reuseaddr TCP:{svc}:8080\"]\n"
                       f"    depends_on: [{svc}]\n    profiles: [{rn}]\n    restart: unless-stopped\n"
                       "    read_only: true\n    security_opt: [no-new-privileges:true]\n    cap_drop: [ALL]\n"
                       "    mem_limit: 32m\n    pids_limit: 64\n")
    if proxy_only:  # the proxy (and the trace store, when its profile runs) join the agent's network: nothing else does
        out.append(f"  litellm:\n    networks: [default, {net}]\n  langfuse-web:\n    networks: [default, {net}]\n\n"
                   f"networks:\n  {net}:\n    internal: true   # no route out; only services on it are reachable\n")
    return "".join(out)


K8S_CLAUDE_DOCKER = (  # entrypoint drops root itself, hence runAsNonRoot: false
    "      - {op: add, path: /spec/template/spec/containers/0/securityContext,\n"
    "         value: {allowPrivilegeEscalation: false,\n"
    f"                 capabilities: {{drop: [ALL], add: [{', '.join(CLAUDE_DOCKER_CAPS)}]}}}}}}\n"
    "      - {op: add, path: /spec/template/spec/securityContext/runAsNonRoot, value: false}\n"
)


# runtime name -> (extra compose env, compose guardrail keys, k8s JSON patches)
RUNTIME_EXTRAS = {
    "claude-docker": (',\n                  HOST_UID: "10001", HOST_GID: "10001"', CLAUDE_DOCKER_GUARDRAILS,
                      K8S_CLAUDE_DOCKER),
}


def gen_k8s(name: str, runtime: str = "generic", prefix: str | None = None, tag: str = "dev", extra: str = "",
            components: list[str] | None = None) -> str:
    # the runtime label keeps selectors apart when one harness has overlays on several runtimes
    return (GENERATED.format(src="harnesses.toml") +
            "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\n"
            f"namePrefix: {prefix or name}-\n"
            f"labels: [{{pairs: {{harness: {name}, runtime: {runtime}}}, includeSelectors: true}}]\n"
            f"resources: [../../agent]\n" + (f"components: [{', '.join(components)}]\n" if components else "") +
            f"images: [{{name: agentrt/HARNESS, newName: agentrt/{name}, newTag: {tag}}}]\n"
            "patches:\n  - target: {kind: Deployment}\n    patch: |-\n"
            f"      - {{op: add, path: /spec/template/spec/containers/0/env/-, value: {{name: OTEL_SERVICE_NAME, "
            f"value: agent-{name}}}}}\n" + extra)


def gen_dependabot() -> str:
    hs = harnesses()
    py = [f"/harnesses/{h['name']}" for h in hs if h["language"] == "python"] + ["/tests", "/quality/inspect",
                                                                                "/quality/audit"]
    node = [f"/harnesses/{h['name']}" for h in hs if h["language"] == "node"]
    docker = ([f"/harnesses/{h['name']}" for h in hs] + [f"/runtimes/{n}" for n in images()] +
              ["/compat/mock-llm"])
    weekly = "    schedule: {interval: weekly, day: monday}\n"

    def block(eco, dirs, group, extra=""):
        lines = "".join(f"      - {d}\n" for d in dirs)
        return (f"  - package-ecosystem: {eco}\n    directories:\n{lines}{weekly}{extra}"
                f"    groups:\n      {group}:\n        patterns: [\"*\"]\n\n")

    return (GENERATED.format(src="harnesses.toml") +
            "# Weekly, grouped dependency updates; CI's conformance job validates them against the mock LLM.\n"
            "version: 2\nupdates:\n" +
            block("uv", py, "python", "    open-pull-requests-limit: 10\n") +
            (block("npm", node, "node") if node else "") +
            f"  - package-ecosystem: github-actions\n    directory: /\n{weekly}    groups:\n      actions:\n"
            "        patterns: [\"*\"]\n\n" +
            block("docker", docker, "base-images") +
            block("docker-compose", ["/runtimes/docker-local"], "compose-images").rstrip() + "\n")


def generated_files() -> dict[pathlib.Path, str]:
    files = {ROOT / "runtimes/docker-local/litellm.yaml": gen_litellm(),
             ROOT / "runtimes/docker-local/docker-compose.harnesses.yml": gen_compose(),
             ROOT / ".github/dependabot.yml": gen_dependabot()}
    for n in names():
        files[ROOT / f"runtimes/k8s/overlays/{n}/kustomization.yaml"] = gen_k8s(n)
    for r in container_runtimes():  # same harness, the runtime's own image and guardrail flags
        rn = r["name"]
        files[ROOT / f"runtimes/{rn}/docker-compose.yml"] = gen_compose_runtime(r)
        for n in r["harnesses"]:  # overlay dir: <runtime> for one harness, <runtime>-<harness> for several
            d = rn if len(r["harnesses"]) == 1 else f"{rn}-{n}"
            files[ROOT / f"runtimes/k8s/overlays/{d}/kustomization.yaml"] = gen_k8s(
                n, runtime=rn, prefix=d, tag=rn, extra=RUNTIME_EXTRAS.get(rn, ("", "", ""))[2],
                components=["../../components/egress-proxy-only"] if r.get("egress") == "proxy-only" else [])
    return files


def container_runtimes() -> list[dict]:
    return [r for r in runtimes() if r["kind"] == "container"]


def gen(check: bool) -> int:
    stale = []
    for path, content in generated_files().items():
        if not path.exists() or path.read_text() != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    overlays = ROOT / "runtimes/k8s/overlays"
    keep = {p.parent.name for p in generated_files() if p.parent.parent == overlays}
    orphans = [p for p in overlays.iterdir() if p.is_dir() and p.name not in keep] if overlays.exists() else []
    for p in orphans:
        stale.append(p)
        if not check:
            shutil.rmtree(p)
    for p in stale:
        print(("stale: " if check else "wrote: ") + str(p.relative_to(ROOT)))
    return 1 if (check and stale) else 0


# ---------------------------------------------------------------- scaffold

def new_harness(name: str, language: str) -> None:
    if not NAME_RE.match(name):
        sys.exit("name must match [a-z][a-z0-9-]{1,30}")
    if name in names():
        sys.exit(f"harness {name} already exists")
    dest, tmpl = ROOT / "harnesses" / name, ROOT / "harnesses/_templates" / language
    if not tmpl.is_dir():
        sys.exit(f"no template for {language}: {tmpl}")
    shutil.copytree(tmpl, dest, ignore=shutil.ignore_patterns("node_modules", ".venv", "dist", "__pycache__"))
    for f in dest.rglob("*"):
        if f.is_file():
            txt = f.read_text()
            if "__HARNESS__" in txt:
                f.write_text(txt.replace("__HARNESS__", name))
    index = min(set(range(1, 20)) - {h["index"] for h in harnesses()})
    with HARNESS_FILE.open("a") as fh:
        fh.write(f'\n[[harness]]\nname = "{name}"\nindex = {index}\nlanguage = "{language}"\n'
                 f'package = "TODO"   # framework package whose version is reported\n'
                 f'repo = "TODO/TODO"   # upstream GitHub repo\nlicence = "TODO"\n')
    if language == "python":
        subprocess.run(["uv", "sync", "-q"], cwd=dest, check=True)  # lock + .venv (perf starts .venv/bin/uvicorn)
    else:
        subprocess.run(["npm", "install", "--silent"], cwd=dest, check=True)
        subprocess.run(["npm", "run", "-s", "build"], cwd=dest, check=True)
    gen(check=False)
    print(f"\nScaffolded harnesses/{name} (index {index}, {language}). It already passes the contract with a plain\n"
          f"OpenAI-SDK tool loop. Next: replace agent.{'py' if language == 'python' else 'ts'} with the framework,\n"
          f"fill package/repo/licence in harnesses.toml, then: make test-native HARNESS={name}")


# ---------------------------------------------------------------- CLI

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("names")
    p = sub.add_parser("port"); p.add_argument("harness"); p.add_argument("purpose")  # noqa: E702
    p = sub.add_parser("get"); p.add_argument("harness"); p.add_argument("field")  # noqa: E702
    p = sub.add_parser("models")
    p.add_argument("--qa", action="store_true"); p.add_argument("--red-team", action="store_true")  # noqa: E702
    p.add_argument("--real", action="store_true", help="exclude mock")
    p.add_argument("--configured", action="store_true", help="only aliases whose env vars are set (.env loaded)")
    sub.add_parser("model-env-vars", help="all env vars referenced by models.toml")
    p = sub.add_parser("gen"); p.add_argument("--check", action="store_true")  # noqa: E702
    p = sub.add_parser("run-args", help="docker run guardrail flags of a container runtime, one per line")
    p.add_argument("runtime")
    p = sub.add_parser("egress", help="egress mode of a container runtime: open | proxy-only")
    p.add_argument("runtime")
    p = sub.add_parser("new-harness"); p.add_argument("name"); p.add_argument("language", choices=["python", "node"])  # noqa: E702
    a = ap.parse_args()
    if a.cmd == "names":
        print(" ".join(names()))
    elif a.cmd == "port":  # purpose: a [ports] key, or the name of a container runtime
        rts = {r["name"]: r for r in container_runtimes()}
        print(runtime_port(rts[a.purpose], a.harness) if a.purpose in rts else port(a.harness, a.purpose))
    elif a.cmd == "get":
        print(harness(a.harness)[a.field])
    elif a.cmd == "model-env-vars":
        print(" ".join(sorted({v for m in models() for v in model_env_vars(m)})))
    elif a.cmd == "models":
        if a.configured:
            load_dotenv()
        ms = [m for m in models() if (not a.qa or m.get("default_qa")) and (not a.red_team or m.get("red_team"))
              and (not a.real or m["kind"] != "mock") and (not a.configured or not missing_env(m))]
        print(",".join(m["alias"] for m in ms))
    elif a.cmd == "gen":
        sys.exit(gen(a.check))
    elif a.cmd == "run-args":
        print("\n".join(run_args(a.runtime)))
    elif a.cmd == "egress":
        print(egress(a.runtime))
    elif a.cmd == "new-harness":
        new_harness(a.name, a.language)


if __name__ == "__main__":
    main()
